eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://discovery:8761/eureka

management:
    endpoints:
        web:
            exposure:
                include: "*"
